server:
  port: 8083

spring:
  flyway:
    locations: classpath:db/migration/sql
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/docker-mysql
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 5
  cloud:
    stream:
      bindings:
        req-received:
          destination: queue.log.messages
        req-sent:
          destination: queue.messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
